//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "file_entities")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub file_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub entity_id: i64,
    #[sea_orm(
        belongs_to,
        from = "entity_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub entities: BelongsTo<super::entities::Entity>,
    #[sea_orm(
        belongs_to,
        from = "file_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub files: BelongsTo<super::files::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
