//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "groups")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub name: String,
    pub max_storage: Option<i64>,
    pub speed_limit: Option<i64>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub permissions: Vec<u8>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub settings: Option<Json>,
    pub storage_policy_id: Option<i64>,
    #[sea_orm(
        belongs_to,
        from = "storage_policy_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub storage_policies: BelongsTo<Option<super::storage_policies::Entity>>,
    #[sea_orm(has_many)]
    pub users: HasMany<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
