//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0
#![cfg_attr(
    not(test),
    deny(
        clippy::unwrap_used,
        clippy::unreachable,
        clippy::expect_used,
        clippy::panic,
        clippy::unimplemented,
        clippy::todo
    )
)]

pub mod prelude;

pub mod dav_accounts;
pub mod direct_links;
pub mod entities;
pub mod file_entities;
pub mod files;
pub mod fs_events;
pub mod groups;
pub mod metadata;
pub mod nodes;
pub mod oauth_clients;
pub mod oauth_grants;
pub mod passkeys;
pub mod settings;
pub mod shares;
pub mod storage_policies;
pub mod tasks;
pub mod users;
