//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "nodes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub status: String,
    pub name: String,
    pub r#type: String,
    pub server: Option<String>,
    pub slave_key: Option<String>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub capabilities: Vec<u8>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub settings: Option<Json>,
    pub weight: i64,
    #[sea_orm(has_many)]
    pub storage_policies: HasMany<super::storage_policies::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
