//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "storage_policies")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub name: String,
    pub r#type: String,
    pub server: Option<String>,
    pub bucket_name: Option<String>,
    pub is_private: Option<bool>,
    #[sea_orm(column_type = "Text", nullable)]
    pub access_key: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub secret_key: Option<String>,
    pub max_size: Option<i64>,
    pub dir_name_rule: Option<String>,
    pub file_name_rule: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub settings: Option<Json>,
    pub node_id: Option<i64>,
    #[sea_orm(has_many)]
    pub entities: HasMany<super::entities::Entity>,
    #[sea_orm(has_many)]
    pub files: HasMany<super::files::Entity>,
    #[sea_orm(has_many)]
    pub groups: HasMany<super::groups::Entity>,
    #[sea_orm(
        belongs_to,
        from = "node_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub nodes: BelongsTo<Option<super::nodes::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
