//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(unique)]
    pub email: String,
    pub nick: String,
    pub password: Option<String>,
    pub status: String,
    pub storage: i64,
    pub two_factor_secret: Option<String>,
    pub avatar: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub settings: Option<Json>,
    pub group_users: i64,
    #[sea_orm(has_many)]
    pub dav_accounts: HasMany<super::dav_accounts::Entity>,
    #[sea_orm(has_many)]
    pub entities: HasMany<super::entities::Entity>,
    #[sea_orm(has_many)]
    pub files: HasMany<super::files::Entity>,
    #[sea_orm(has_many)]
    pub fs_events: HasMany<super::fs_events::Entity>,
    #[sea_orm(
        belongs_to,
        from = "group_users",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub groups: BelongsTo<super::groups::Entity>,
    #[sea_orm(has_many)]
    pub oauth_grants: HasMany<super::oauth_grants::Entity>,
    #[sea_orm(has_many)]
    pub passkeys: HasMany<super::passkeys::Entity>,
    #[sea_orm(has_many)]
    pub shares: HasMany<super::shares::Entity>,
    #[sea_orm(has_many)]
    pub tasks: HasMany<super::tasks::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
