//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.41

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "background_tasks")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub kind: String,
    pub status: String,
    pub creator_user_id: Option<i64>,
    pub team_id: Option<i64>,
    pub share_id: Option<i64>,
    pub display_name: String,
    #[sea_orm(column_type = "Text")]
    pub payload_json: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub result_json: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub steps_json: Option<String>,
    pub progress_current: i64,
    pub progress_total: i64,
    pub status_text: Option<String>,
    pub attempt_count: i64,
    pub max_attempts: i64,
    pub next_run_at: DateTimeWithTimeZone,
    pub processing_token: i64,
    pub processing_started_at: Option<DateTimeWithTimeZone>,
    pub last_heartbeat_at: Option<DateTimeWithTimeZone>,
    pub lease_expires_at: Option<DateTimeWithTimeZone>,
    pub started_at: Option<DateTimeWithTimeZone>,
    pub finished_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_error: Option<String>,
    pub failure_can_retry: Option<bool>,
    pub expires_at: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text", nullable)]
    pub runtime_json: Option<String>,
    #[sea_orm(has_one)]
    pub storage_migration_checkpoints: HasOne<super::storage_migration_checkpoints::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
