//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.41

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "blob_media_metadata")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub blob_id: i64,
    pub blob_hash: String,
    pub kind: String,
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub metadata_json: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_message: Option<String>,
    pub parser: String,
    pub parser_version: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "blob_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub file_blobs: HasOne<super::file_blobs::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
