//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.41

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "entity_properties")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "idx_entity_properties_unique")]
    pub entity_type: String,
    #[sea_orm(unique_key = "idx_entity_properties_unique")]
    pub entity_id: i64,
    #[sea_orm(unique_key = "idx_entity_properties_unique")]
    pub namespace: String,
    #[sea_orm(unique_key = "idx_entity_properties_unique")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub value: Option<String>,
}

impl ActiveModelBehavior for ActiveModel {}
