//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.41

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "external_auth_email_verification_flows")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub provider_id: i64,
    pub identity_namespace: String,
    pub subject: String,
    pub target_email: Option<String>,
    pub display_name_snapshot: Option<String>,
    pub preferred_username_snapshot: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub return_path: Option<String>,
    #[sea_orm(unique)]
    pub flow_token_hash: String,
    #[sea_orm(unique)]
    pub verification_token_hash: Option<String>,
    pub email_requested_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub expires_at: DateTimeWithTimeZone,
    pub consumed_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(
        belongs_to,
        from = "provider_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub external_auth_providers: HasOne<super::external_auth_providers::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
