//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.41

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "external_auth_identities")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "idx_external_auth_identities_user_provider")]
    pub user_id: i64,
    #[sea_orm(unique_key = "idx_external_auth_identities_provider_subject")]
    pub provider_id: i64,
    #[sea_orm(unique_key = "idx_external_auth_identities_namespace_subject")]
    pub identity_namespace: String,
    #[sea_orm(unique_key = "idx_external_auth_identities_provider_subject")]
    pub subject: String,
    pub email_snapshot: Option<String>,
    pub display_name_snapshot: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub last_login_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(
        belongs_to,
        from = "provider_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub external_auth_providers: HasOne<super::external_auth_providers::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
