//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.41

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "external_auth_providers")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "idx_external_auth_providers_kind_key")]
    pub key: String,
    pub display_name: String,
    pub icon_url: Option<String>,
    #[sea_orm(unique_key = "idx_external_auth_providers_kind_key")]
    pub provider_kind: String,
    pub protocol: String,
    pub issuer_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub authorization_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub token_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub userinfo_url: Option<String>,
    pub client_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub client_secret: Option<String>,
    pub scopes: String,
    pub enabled: bool,
    pub auto_provision_enabled: bool,
    pub auto_link_verified_email_enabled: bool,
    pub require_email_verified: bool,
    pub subject_claim: Option<String>,
    pub username_claim: Option<String>,
    pub display_name_claim: Option<String>,
    pub email_claim: Option<String>,
    pub email_verified_claim: Option<String>,
    pub groups_claim: Option<String>,
    pub avatar_url_claim: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub allowed_domains: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub options: String,
    #[sea_orm(has_many)]
    pub external_auth_email_verification_flows:
        HasMany<super::external_auth_email_verification_flows::Entity>,
    #[sea_orm(has_many)]
    pub external_auth_identities: HasMany<super::external_auth_identities::Entity>,
    #[sea_orm(has_many)]
    pub external_auth_login_flows: HasMany<super::external_auth_login_flows::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
