//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.41

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "external_auth_login_flows")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub provider_id: i64,
    #[sea_orm(unique)]
    pub state_hash: String,
    pub nonce: Option<String>,
    pub pkce_verifier: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub redirect_uri: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub return_path: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub expires_at: DateTimeWithTimeZone,
    pub consumed_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(
        belongs_to,
        from = "provider_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub external_auth_providers: HasOne<super::external_auth_providers::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
