//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.41

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "file_blobs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "idx_file_blobs_hash_policy")]
    pub hash: String,
    pub size: i64,
    #[sea_orm(unique_key = "idx_file_blobs_hash_policy")]
    pub policy_id: i64,
    pub storage_path: String,
    pub thumbnail_path: Option<String>,
    pub thumbnail_processor: Option<String>,
    pub thumbnail_version: Option<String>,
    pub ref_count: i64,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(has_one)]
    pub blob_media_metadata: HasOne<super::blob_media_metadata::Entity>,
    #[sea_orm(has_many)]
    pub file_versions: HasMany<super::file_versions::Entity>,
    #[sea_orm(has_many)]
    pub files: HasMany<super::files::Entity>,
    #[sea_orm(
        belongs_to,
        from = "policy_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub storage_policies: HasOne<super::storage_policies::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
