//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.41

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "files")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "idx_files_unique_live_name")]
    pub name: String,
    pub folder_id: Option<i64>,
    pub team_id: Option<i64>,
    pub blob_id: i64,
    pub size: i64,
    pub owner_user_id: Option<i64>,
    pub created_by_user_id: Option<i64>,
    pub created_by_username: String,
    pub mime_type: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub is_locked: bool,
    pub extension: String,
    pub compound_extension: Option<String>,
    pub file_category: String,
    #[sea_orm(
        belongs_to,
        from = "blob_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub file_blobs: HasOne<super::file_blobs::Entity>,
    #[sea_orm(
        belongs_to,
        from = "folder_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub folders: HasOne<super::folders::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Users2",
        from = "created_by_user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub users_2: HasOne<super::users::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Users1",
        from = "owner_user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub users_1: HasOne<super::users::Entity>,
    #[sea_orm(has_many)]
    pub wopi_sessions: HasMany<super::wopi_sessions::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
