//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.41

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "file_versions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub file_id: i64,
    pub blob_id: i64,
    pub version: i64,
    pub size: i64,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "blob_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub file_blobs: HasOne<super::file_blobs::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
