//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.41

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "folders")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "idx_folders_unique_live_name")]
    pub name: String,
    pub parent_id: Option<i64>,
    pub team_id: Option<i64>,
    pub owner_user_id: Option<i64>,
    pub created_by_user_id: Option<i64>,
    pub created_by_username: String,
    pub policy_id: Option<i64>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub is_locked: bool,
    #[sea_orm(has_many)]
    pub files: HasMany<super::files::Entity>,
    #[sea_orm(
        self_ref,
        relation_enum = "SelfRef",
        from = "parent_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub folders: HasOne<Entity>,
    #[sea_orm(
        belongs_to,
        from = "policy_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub storage_policies: HasOne<super::storage_policies::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Users2",
        from = "created_by_user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub users_2: HasOne<super::users::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Users1",
        from = "owner_user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub users_1: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
