//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.41

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "follower_enrollment_sessions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub managed_follower_id: i64,
    #[sea_orm(unique)]
    pub token_hash: String,
    #[sea_orm(unique)]
    pub ack_token_hash: String,
    pub expires_at: DateTimeWithTimeZone,
    pub redeemed_at: Option<DateTimeWithTimeZone>,
    pub acked_at: Option<DateTimeWithTimeZone>,
    pub invalidated_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "managed_follower_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub managed_followers: HasOne<super::managed_followers::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
