//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.41

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "mail_outbox")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub template_code: String,
    pub to_address: String,
    pub to_name: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub payload_json: String,
    pub status: String,
    pub attempt_count: i64,
    pub next_attempt_at: DateTimeWithTimeZone,
    pub processing_started_at: Option<DateTimeWithTimeZone>,
    pub sent_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_error: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
