//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.41

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "managed_followers")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    pub base_url: String,
    #[sea_orm(unique)]
    pub access_key: String,
    pub secret_key: String,
    pub is_enabled: bool,
    #[sea_orm(column_type = "Text")]
    pub last_capabilities: String,
    #[sea_orm(column_type = "Text")]
    pub last_error: String,
    pub last_checked_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub transport_mode: String,
    #[sea_orm(column_type = "Text")]
    pub tunnel_last_error: String,
    pub tunnel_last_seen_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(has_many)]
    pub follower_enrollment_sessions: HasMany<super::follower_enrollment_sessions::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
