//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.41

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "mfa_login_flows")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub flow_token_hash: String,
    pub user_id: i64,
    pub user_session_version: i64,
    pub first_factor: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub return_path: Option<String>,
    pub ip_address: Option<String>,
    pub user_agent: Option<String>,
    pub attempt_count: i64,
    pub expires_at: DateTimeWithTimeZone,
    pub consumed_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub mfa_email_codes: HasMany<super::mfa_email_codes::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
