//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.41

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "resource_locks")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub token: String,
    pub entity_type: String,
    pub entity_id: i64,
    pub path: String,
    pub owner_id: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub owner_info: Option<String>,
    pub timeout_at: Option<DateTimeWithTimeZone>,
    pub shared: bool,
    pub deep: bool,
    pub created_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
