//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.41

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "storage_policy_group_items")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "idx_spgi_group_priority")]
    pub group_id: i64,
    #[sea_orm(unique_key = "idx_spgi_group_policy")]
    pub policy_id: i64,
    #[sea_orm(unique_key = "idx_spgi_group_priority")]
    pub priority: i64,
    pub min_file_size: i64,
    pub max_file_size: i64,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "policy_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub storage_policies: HasOne<super::storage_policies::Entity>,
    #[sea_orm(
        belongs_to,
        from = "group_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub storage_policy_groups: HasOne<super::storage_policy_groups::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
