//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.41

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "storage_policy_authorization_flows")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub provider: String,
    pub policy_id: Option<i64>,
    pub created_by_user_id: i64,
    #[sea_orm(unique)]
    pub state_hash: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub pkce_verifier: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub redirect_uri: String,
    #[sea_orm(column_type = "Text")]
    pub scopes: String,
    #[sea_orm(column_type = "Text")]
    pub context: String,
    pub status: String,
    pub created_at: DateTimeWithTimeZone,
    pub expires_at: DateTimeWithTimeZone,
    pub consumed_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(
        belongs_to,
        from = "policy_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub storage_policies: HasOne<super::storage_policies::Entity>,
    #[sea_orm(
        belongs_to,
        from = "created_by_user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
