//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.41

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "storage_migration_checkpoints")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub task_id: i64,
    pub source_policy_id: i64,
    pub target_policy_id: i64,
    pub plan_hash: String,
    pub stage: String,
    pub last_processed_blob_id: i64,
    pub scanned_blobs: i64,
    pub migrated_blobs: i64,
    pub merged_blobs: i64,
    pub skipped_blobs: i64,
    pub failed_blobs: i64,
    pub migrated_bytes: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_error: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub renamed_opaque_blobs: i64,
    #[sea_orm(
        belongs_to,
        from = "task_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub background_tasks: HasOne<super::background_tasks::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
