//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.41

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "storage_policy_credentials")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "idx_storage_policy_credentials_policy_provider_kind")]
    pub policy_id: i64,
    #[sea_orm(unique_key = "idx_storage_policy_credentials_policy_provider_kind")]
    pub provider: String,
    #[sea_orm(unique_key = "idx_storage_policy_credentials_policy_provider_kind")]
    pub credential_kind: String,
    pub account_label: Option<String>,
    pub subject: Option<String>,
    pub tenant_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub scopes: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub access_token_ciphertext: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub refresh_token_ciphertext: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub metadata: String,
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub status_reason: Option<String>,
    pub expires_at: Option<DateTimeWithTimeZone>,
    pub authorized_at: Option<DateTimeWithTimeZone>,
    pub last_refreshed_at: Option<DateTimeWithTimeZone>,
    pub last_validated_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "policy_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub storage_policies: HasOne<super::storage_policies::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
