//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.41

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "storage_policies")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    pub driver_type: String,
    pub endpoint: String,
    pub bucket: String,
    pub access_key: String,
    pub secret_key: String,
    pub base_path: String,
    pub remote_node_id: Option<i64>,
    pub max_file_size: i64,
    #[sea_orm(column_type = "Text")]
    pub allowed_types: String,
    #[sea_orm(column_type = "Text")]
    pub options: String,
    pub is_default: bool,
    pub chunk_size: i64,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub remote_storage_target_key: Option<String>,
    #[sea_orm(has_many)]
    pub file_blobs: HasMany<super::file_blobs::Entity>,
    #[sea_orm(has_many)]
    pub folders: HasMany<super::folders::Entity>,
    #[sea_orm(has_many)]
    pub storage_connector_application_configs:
        HasMany<super::storage_connector_application_configs::Entity>,
    #[sea_orm(has_many)]
    pub storage_policy_authorization_flows:
        HasMany<super::storage_policy_authorization_flows::Entity>,
    #[sea_orm(has_many)]
    pub storage_policy_credentials: HasMany<super::storage_policy_credentials::Entity>,
    #[sea_orm(has_many)]
    pub storage_policy_group_items: HasMany<super::storage_policy_group_items::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
