//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.41

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "storage_connector_application_configs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "idx_storage_connector_app_configs_policy_provider")]
    pub policy_id: i64,
    #[sea_orm(unique_key = "idx_storage_connector_app_configs_policy_provider")]
    pub provider: String,
    pub tenant_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub scopes: String,
    pub client_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub client_secret_ciphertext: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub metadata: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "policy_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub storage_policies: HasOne<super::storage_policies::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
