//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.41

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "system_config")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub key: String,
    #[sea_orm(column_type = "Text")]
    pub value: String,
    pub value_type: String,
    pub requires_restart: bool,
    pub is_sensitive: bool,
    pub source: String,
    pub namespace: String,
    pub category: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub updated_at: DateTimeWithTimeZone,
    pub updated_by: Option<i64>,
    pub visibility: String,
}

impl ActiveModelBehavior for ActiveModel {}
