//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.41

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "tags")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "idx_tags_personal_unique")]
    pub scope_type: String,
    #[sea_orm(unique_key = "idx_tags_personal_unique")]
    pub owner_user_id: Option<i64>,
    #[sea_orm(unique_key = "idx_tags_team_unique")]
    pub team_id: Option<i64>,
    pub name: String,
    #[sea_orm(unique_key = "idx_tags_personal_unique")]
    pub normalized_name: String,
    pub color: String,
    pub sort_order: i64,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "team_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub teams: HasOne<super::teams::Entity>,
    #[sea_orm(
        belongs_to,
        from = "owner_user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
