//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.41

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "teams")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    pub description: String,
    pub created_by: i64,
    pub storage_used: i64,
    pub storage_quota: i64,
    pub policy_group_id: Option<i64>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub archived_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(
        belongs_to,
        from = "policy_group_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub storage_policy_groups: HasOne<super::storage_policy_groups::Entity>,
    #[sea_orm(has_many)]
    pub tags: HasMany<super::tags::Entity>,
    #[sea_orm(has_many)]
    pub team_members: HasMany<super::team_members::Entity>,
    #[sea_orm(
        belongs_to,
        from = "created_by",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub users: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
