//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.41

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "upload_session_parts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "uq_upload_session_parts_upload_id_part_number")]
    pub upload_id: String,
    #[sea_orm(unique_key = "uq_upload_session_parts_upload_id_part_number")]
    pub part_number: i64,
    pub etag: String,
    pub size: i64,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "upload_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub upload_sessions: HasOne<super::upload_sessions::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
