//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.41

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "upload_sessions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub user_id: i64,
    pub team_id: Option<i64>,
    pub filename: String,
    pub total_size: i64,
    pub chunk_size: i64,
    pub total_chunks: i64,
    pub received_count: i64,
    pub folder_id: Option<i64>,
    pub policy_id: i64,
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub object_temp_key: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub object_multipart_id: Option<String>,
    pub file_id: Option<i64>,
    pub created_at: DateTimeWithTimeZone,
    pub expires_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub frontend_client_id: Option<String>,
    #[sea_orm(has_many)]
    pub upload_session_parts: HasMany<super::upload_session_parts::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
