//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.41

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub username: String,
    #[sea_orm(unique)]
    pub email: String,
    pub password_hash: String,
    pub role: String,
    pub status: String,
    pub session_version: i64,
    pub email_verified_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(unique)]
    pub pending_email: Option<String>,
    pub storage_used: i64,
    pub storage_quota: i64,
    pub policy_group_id: Option<i64>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text", nullable)]
    pub config: Option<String>,
    pub must_change_password: bool,
    #[sea_orm(has_many)]
    pub auth_sessions: HasMany<super::auth_sessions::Entity>,
    #[sea_orm(has_many)]
    pub contact_verification_tokens: HasMany<super::contact_verification_tokens::Entity>,
    #[sea_orm(has_many)]
    pub external_auth_identities: HasMany<super::external_auth_identities::Entity>,
    #[sea_orm(has_many)]
    pub mfa_email_codes: HasMany<super::mfa_email_codes::Entity>,
    #[sea_orm(has_many)]
    pub mfa_factors: HasMany<super::mfa_factors::Entity>,
    #[sea_orm(has_many)]
    pub mfa_login_flows: HasMany<super::mfa_login_flows::Entity>,
    #[sea_orm(has_many)]
    pub mfa_recovery_codes: HasMany<super::mfa_recovery_codes::Entity>,
    #[sea_orm(has_many)]
    pub mfa_totp_setup_flows: HasMany<super::mfa_totp_setup_flows::Entity>,
    #[sea_orm(has_many)]
    pub passkeys: HasMany<super::passkeys::Entity>,
    #[sea_orm(has_many)]
    pub shares: HasMany<super::shares::Entity>,
    #[sea_orm(has_many)]
    pub storage_policy_authorization_flows:
        HasMany<super::storage_policy_authorization_flows::Entity>,
    #[sea_orm(has_many)]
    pub tags: HasMany<super::tags::Entity>,
    #[sea_orm(has_many)]
    pub team_members: HasMany<super::team_members::Entity>,
    #[sea_orm(has_many)]
    pub teams: HasMany<super::teams::Entity>,
    #[sea_orm(has_many)]
    pub upload_sessions: HasMany<super::upload_sessions::Entity>,
    #[sea_orm(has_one)]
    pub user_profiles: HasOne<super::user_profiles::Entity>,
    #[sea_orm(has_many)]
    pub webdav_accounts: HasMany<super::webdav_accounts::Entity>,
    #[sea_orm(has_many)]
    pub wopi_sessions: HasMany<super::wopi_sessions::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
