//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.41

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "user_invitations")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub email: String,
    #[sea_orm(unique)]
    pub token_hash: String,
    pub status: String,
    pub invited_by: i64,
    pub accepted_user_id: Option<i64>,
    pub expires_at: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub accepted_at: Option<DateTimeWithTimeZone>,
    pub revoked_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Users2",
        from = "accepted_user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub users_2: HasOne<super::users::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Users1",
        from = "invited_by",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users_1: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
