# --- Commit ---
# [commit]
# custom_prompt = ""
# show_diff_preview = true

[commit.convention]
style = "conventional"
types = ["feat", "fix", "docs", "style", "refactor", "perf", "test", "chore", "ci"]
template = "{type}({scope}): {subject}"
extra_prompt = "Please write the commit message in English. Start with a brief summary and then describe the functions in detail with list."
