//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.41

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "dav_accounts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub uri: String,
    #[sea_orm(unique_key = "davaccount_owner_id_password")]
    pub password: String,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub options: Vec<u8>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub props: Option<Json>,
    #[sea_orm(unique_key = "davaccount_owner_id_password")]
    pub owner_id: i64,
    #[sea_orm(
        belongs_to,
        from = "owner_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub users: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
