//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.41

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "public", table_name = "entities")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub r#type: i64,
    #[sea_orm(column_type = "Text")]
    pub source: String,
    pub size: i64,
    pub reference_count: i64,
    pub upload_session_id: Option<Uuid>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub recycle_options: Option<Json>,
    pub storage_policy_entities: i64,
    pub created_by: Option<i64>,
    #[sea_orm(
        belongs_to,
        from = "storage_policy_entities",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub storage_policies: HasOne<super::storage_policies::Entity>,
    #[sea_orm(
        belongs_to,
        from = "created_by",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub users: HasOne<super::users::Entity>,
    #[sea_orm(has_many, via = "file_entities")]
    pub files: HasMany<super::files::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
