//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "files")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub r#type: i64,
    #[sea_orm(unique_key = "file_file_children_name")]
    pub name: String,
    pub size: i64,
    pub primary_entity: Option<i64>,
    pub is_symbolic: bool,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub props: Option<Json>,
    #[sea_orm(unique_key = "file_file_children_name")]
    pub file_children: Option<i64>,
    pub storage_policy_files: Option<i64>,
    pub owner_id: i64,
    #[sea_orm(has_many)]
    pub direct_links: HasMany<super::direct_links::Entity>,
    #[sea_orm(
        self_ref,
        relation_enum = "SelfRef",
        from = "file_children",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub files: BelongsTo<Option<Entity>>,
    #[sea_orm(has_many)]
    pub metadata: HasMany<super::metadata::Entity>,
    #[sea_orm(has_many)]
    pub shares: HasMany<super::shares::Entity>,
    #[sea_orm(
        belongs_to,
        from = "storage_policy_files",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub storage_policies: BelongsTo<Option<super::storage_policies::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "owner_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub users: BelongsTo<super::users::Entity>,
    #[sea_orm(has_many, via = "file_entities")]
    pub entities: HasMany<super::entities::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
