//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.41

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "metadata")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(unique_key = "metadata_file_id_name")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub value: String,
    pub is_public: bool,
    #[sea_orm(unique_key = "metadata_file_id_name")]
    pub file_id: i64,
    #[sea_orm(
        belongs_to,
        from = "file_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub files: HasOne<super::files::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
