//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.41

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "oauth_clients")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(unique)]
    pub guid: String,
    pub secret: String,
    pub name: String,
    pub homepage_url: Option<String>,
    #[sea_orm(column_type = "JsonBinary")]
    pub redirect_uris: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub scopes: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub props: Json,
    pub is_enabled: bool,
    #[sea_orm(has_many)]
    pub oauth_grants: HasMany<super::oauth_grants::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
