//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.41

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "oauth_grants")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "JsonBinary")]
    pub scopes: Json,
    pub last_used_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(unique_key = "oauthgrant_user_id_client_id")]
    pub client_id: i64,
    #[sea_orm(unique_key = "oauthgrant_user_id_client_id")]
    pub user_id: i64,
    #[sea_orm(
        belongs_to,
        from = "client_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub oauth_clients: HasOne<super::oauth_clients::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub users: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
