//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.41

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "public", table_name = "shares")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub password: Option<String>,
    pub views: i64,
    pub downloads: i64,
    pub expires: Option<DateTimeWithTimeZone>,
    pub remain_downloads: Option<i64>,
    pub file_shares: Option<i64>,
    pub user_shares: Option<i64>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub props: Option<Json>,
    #[sea_orm(
        belongs_to,
        from = "file_shares",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub files: HasOne<super::files::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_shares",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub users: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
