//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "tasks")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub r#type: String,
    pub status: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub public_state: Json,
    #[sea_orm(column_type = "Text", nullable)]
    pub private_state: Option<String>,
    pub correlation_id: Option<Uuid>,
    pub user_tasks: Option<i64>,
    #[sea_orm(
        belongs_to,
        from = "user_tasks",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub users: BelongsTo<Option<super::users::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
